#!/bin/bash

set -e

# Remove files generated by cmake
find . -type d -name CMakeFiles -exec rm -rf {} +
find . -name Makefile -exec rm {} +

#Remove artifacts generated by buildDeb and make
find . -type d -name build -exec rm -rf {} +
find . -type d -name output -exec rm -rf {} +

#Remove any dependencies downloaded
find . -name boost*.deb -exec rm \;
find . -type d -name curl* -exec rm -rf \;


