#!/bin/bash

set -e

BOOSTVER=1.55
CURLVER=7.36.0
boostStr="boost-$BOOSTVER"
curlStr="curl-$CURLVER"

# Remove files generated by cmake
find . -type d -name CMakeFiles -exec rm -rf {} +
find . -name Makefile -exec rm {} +

#Remove artifacts generated by buildDeb and make
find . -type d -name build -exec rm -rf {} +
find . -type d -name output -exec rm -rf {} +

#Remove any dependencies downloaded
find . -name "$boostStr*.deb*" -exec rm {} +
find . -name "$curlStr*.gz*" -exec rm {} +
find . -type d -name "$curlStr*" -exec rm -rf {} +


